# name: Course Monitor Workflow

# on:
#   schedule:
#     - cron: "0 */6 * * *"  # Runs every 6 hours
#   workflow_dispatch:  # Allows manual triggering from the GitHub Actions UI

jobs:
  monitor-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        nohup python script.py &
